### ISSUE TITLE
Deployable Engines Plugin does not uninstall when uninstalling Kerbal Atomics

### ISSUE THREAD

**Issue by JoESmash** [KSP-CKAN/NetKAN#6607] opened 2018-06-28 11:33 UTC
Hello,

I am pretty sure Deployable Engines Plugin is a dependency for Kerbal Atomics mod. I uninstalled Kerbal Atomics mod, but it did NOT also remove Deployable Engines Plugin. When I go to remove the plugin it does't try to remove anything else with it so it obviously has no reason to still be installed....

Thanks,
JoE Smash

Background
----------

**CKAN Version:** 

**KSP Version:** 

**Operating System:** 

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 

**Affected mods and mod versions:**

Problem
-------

**What steps did you take in CKAN?**

**What did you expect to happen?**

**What happened instead?**

**Screenshots:**

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment] 2018-06-28 14:16
Duplicate of KSP-CKAN/CKAN#978; currently it's not expected that uninstalling a mod would uninstall its dependencies.

**Closed by HebaruSan** 2018-06-28 14:16 UTC

**Comment by JoESmash** [comment] 2018-06-28 15:00
So uninstalling a dependency takes the main mod with it, but if you can't remember that a mod had a dependency, uninstalling said mod leaves the useless dependency behind?

That sounds like a great way to muck up KSP.....I would rethink that.....

**Comment by HebaruSan** [comment] 2018-06-28 15:07
We agree! KSP-CKAN/CKAN#978 has not been closed, in fact it has a one-star label. This is something the team thinks should be done.
