### ISSUE TITLE
Throttle Controlled avionics will not install

### ISSUE THREAD

**Issue by Bit-Fiddler** [KSP-CKAN/NetKAN#4911] opened 2016-11-08 16:04 UTC
the mod reports AT-Utils is missing, and will not install.

**Comment by politas** [comment] 2016-11-09 12:22
What KSP Version are you trying to install it into?

**Comment by Bit-Fiddler** [comment] 2016-11-10 05:59
I have 1.2.1 and if I manually install the mod I do indeed get the "AD" but if I delete the mod I get the error about AT-UTILS.   AT-UTILS is packaged with TCA however so it should not have to look for it, unless it has been split out as I think it is also included with Custom containers and maybe a few other of Alista's mods.

**Comment by Bit-Fiddler** [comment] 2016-11-10 06:02
lol this, and many other mods issues I have found in the last week, just  because I just had to "fix" module manager.  I should have just left MM out of the CKAN and updated it manually. about 50% of my mods do not want to reinstall, but most of them I can sort out the issues on my own.  usually from a stray file left behind when removing the original install of the mod.

**Comment by politas** [comment] 2016-11-10 10:03
You're getting a real course in fixing CKAN issues, here!

**Comment by politas** [comment] 2016-11-10 10:06
So, when you manually installed the mod, did you install the packaged AT-Utils as well?

At some point it gets easier to just delete your entire GameData directory (other than the "Squad" folder, obviously), delete your registry.json, and start from scratch. Obviously, if you've got a lot of manually installed mods, that's a nuisance, but if you move your GameData contents off to an archive location, you can move back your manual mods afterwards.

**Comment by Bit-Fiddler** [comment] 2016-11-20 13:14
just did this...

wiped KSP and working on the rebuild of the mods now.

**Comment by politas** [comment] 2016-11-21 03:07
Closing due to inability to reproduce and issue worked around.

**Closed by politas** 2016-11-21 03:07 UTC
