### ISSUE TITLE
[Bug] Download error installing Harmony 2

### ISSUE THREAD

**Issue by jwvanderbeck** [KSP-CKAN/NetKAN#8531] opened 2021-05-09 22:58 UTC
Background
----------
* Operating System: Windows
* CKAN Version: 1.30.0
* KSP Version: 1.10.1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
When trying to install RP-1, dependencies, and chosen Recommends, the install always fails at the same point with a download error, even after multiple retries.

According to the log it looks to be failing when downloading Harmony 2 as a dependency of Kerbalism.  The zip URL in the log looks corrupt.

```
Downloading "https://github.com/Kerbalism/Kerbalism/releases/download/3.13/Kerbalism-Core_v3.13_for_KSP1.8.0-1.11.9.zip"
Downloading "https://github.com/KSPModdingLibs/HarmonyKSP/releases/download/2.0.4.0/HarmonyKSP_2.0.4.0_for_KSP1.8%2B.zip"
Trying to install RP-0 v1.8.1, but it's not downloaded or download is corrupted
Error during installation!
```

**Steps to reproduce**
* New KSP 1.10.1 install
* Select to install Realistic Progression 1 as per install guide (https://github.com/KSP-RO/RP-0/wiki/RO-&-RP-1-Installation-for-1.10.1)
* In Recommends, choose Kerbalism

**Expected behavior**
Install properly.

```
About to install:

 * Realistic Progression One (RP-1) v1.8.1 (github.com, 46.5 MiB)
 * RSS DateTime Formatter 1.6.1.0 (github.com, 5.8 KiB)
 * Deadly Reentry Continued v7.8.0 (github.com, 930.0 KiB)
 * RO Engines v1.7 (github.com, 167.7 MiB)
 * RO Tanks v2.3 (github.com, 67.6 MiB)
 * RO Capsules v1.3 (github.com, 206.8 MiB)
 * RO Solar v1.1.1 (github.com, 14.5 MiB)
 * B9 Aerospace Procedural Wings - Fork 2:0.401 (spacedock.info, 3.0 MiB)
 * KSP Wheel 1:0.16.14.33 (github.com, 102.0 KiB)
 * PersistentRotation Upgraded 1.9.1.3 (spacedock.info, 52.5 KiB)
 * Hangar Extender 3.6.0 (spacedock.info, 46.4 KiB)
 * Kerbal Alarm Clock v3.13.0.0 (github.com, 1.4 MiB)
 * Kerbal Renamer v1.4.0 (github.com, 11.2 KiB)
 * KSC Switcher v2.0.0.0 (github.com, 28.9 KiB)
 * AtmosphereAutopilot (Fly-By-Wire) v1.5.16 (github.com, 185.5 KiB)
 * Procedural Fairings 1:v1.8.3 (github.com, 5.3 MiB)
 * Procedural Parts v2.1.2 (github.com, 3.7 MiB)
 * RCS Build Aid v1.0.3 (github.com, 75.7 KiB)
 * Real Antennas v1.3.0 (github.com, 100.2 KiB)
 * SCANsat v20.4 (spacedock.info, 19.3 MiB)
 * Extended information about scientific experiments in VAB 1:1.3.4 (spacedock.info, 30.8 KiB)
 * Ship Manifest 6.0.2.0 (github.com, 692.5 KiB)
 * Kerbalism - RealismOverhaul Config v1.0 (github.com, 3.5 MiB)
 * Test Flight 2.0.0 (github.com, 175.8 KiB)
 * Real Solar System Textures - 16384 x 8192 v18.3 (github.com, 1.7 GiB)
 * Module Manager 4.1.4 (ksp.sarbian.com, 61.3 KiB)
 * Realism Overhaul v13.0.1 (github.com, 11.8 MiB)
 * Advanced Jet Engine v2.16.0 (github.com, 652.2 KiB)
 * Ferram Aerospace Research Continued 3:0.16.0.2 (github.com, 867.5 KiB)
 * ModularFlightIntegrator 1.2.7.0 (ksp.sarbian.com, 9.5 KiB)
 * Solver Engines plugin v3.9.0 (github.com, 38.8 KiB)
 * Kerbal Joint Reinforcement Continued v3.5.2 (github.com, 36.4 KiB)
 * RealChute Parachute Systems v1.4.8 (github.com, 2.6 MiB)
 * Real Fuels rf-v12.9.1 (github.com, 404.1 KiB)
 * Community Resource Pack 1.4.2 (github.com, 53.8 KiB)
 * RealHeat v5.1 (github.com, 12.8 KiB)
 * Real Plume 2:v13.3.2 (github.com, 19.3 MiB)
 * SmokeScreen - Extended FX Plugin 2.8.14.0 (ksp.sarbian.com, 28.0 KiB)
 * SXTContinued 2:0.3.29.5 (spacedock.info, 38.1 MiB)
 * Firespitter Core v7.17 (github.com, 28.7 MiB)
 * Firespitter Resources config v7.17 (github.com, 28.7 MiB)
 * Retractable Lifting Surface Module 0.2.1.1 (github.com, 8.4 KiB)
 * Contract Configurator 1.30.5 (github.com, 552.1 KiB)
 * Custom Barn Kit 1.1.21.0 (ksp.sarbian.com, 15.8 KiB)
 * Ven's New Parts v1.15.1 (github.com, 135.7 MiB)
 * Ven's Stock Part Revamp Core v1.15.1 (github.com, 135.7 MiB)
 * Real Solar System v18.1.4 (github.com, 74.2 MiB)
 * Kopernicus Planetary System Modifier 2:release-1.11.1-38 (github.com, 390.9 KiB)
 * DMagic Orbital Science 1.4.3 (spacedock.info, 15.2 MiB)
 * DMModuleScienceAnimateGeneric v0.23 (github.com, 17.6 KiB)
 * MagiCore 1.3.2.3 (spacedock.info, 32.9 KiB)
 * ClickThrough Blocker 1:0.1.10.15 (spacedock.info, 107.3 KiB)
 * Zero MiniAVC 1:1.1.0.1 (spacedock.info, 16.8 KiB)
 * Toolbar Controller 1:0.1.9.4 (spacedock.info, 86.3 KiB)
 * RO Library v1.1.1 (github.com, 66.2 KiB)
 * Textures Unlimited 1.5.10.25 (github.com, 9.7 MiB)
 * B9 Part Switch v2.17.0 (github.com, 95.0 KiB)
 * Patch Manager 0.0.17.2 (github.com, 32.9 KiB)
 * BahamutoD Animation Modules 1:v0.6.6.0 (github.com, 122.6 KiB)
 * SpaceTux Library 0.0.6 (spacedock.info, 483.8 KiB)
 * Kerbalism 3.13 (github.com, 1.2 MiB)
 * Harmony 2 2.0.4.0 (github.com, 307.0 KiB)
Downloading "https://github.com/KSP-RO/RP-0/releases/download/v1.8.1/RP-1-v1.8.1.zip"
Downloading "https://spacedock.info/mod/2525/B9%20Procedural%20Wings%20Modified%20Continued/download/0.401"
Downloading "https://spacedock.info/mod/2660/PersistentRotation%20Upgraded/download/1.9.1.3"
Downloading "https://spacedock.info/mod/1428/HangerExtender/download/3.6.0"
Downloading "https://spacedock.info/mod/129/SCANsat/download/v20.4"
Downloading "https://spacedock.info/mod/2000/Extended%20information%20about%20scientific%20experiments%20in%20VAB/download/1.3.4"
Downloading "https://ksp.sarbian.com/jenkins/job/ModuleManager/159/artifact/ModuleManager-4.1.4.zip"
Downloading "https://ksp.sarbian.com/jenkins/job/ModularFlightIntegrator/35/artifact/ModularFlightIntegrator-1.2.7.0.zip"
Downloading "https://ksp.sarbian.com/jenkins/job/SmokeScreen/87/artifact/SmokeScreen-2.8.14.0.zip"
Downloading "https://spacedock.info/mod/1030/SXTContinued/download/0.3.29.5"
Downloading "https://ksp.sarbian.com/jenkins/job/CustomBarnKit/47/artifact/CustomBarnKit-1.1.21.0.zip"
Downloading "https://spacedock.info/mod/128/DMagic%20Orbital%20Science/download/1.4.3"
Downloading "https://spacedock.info/mod/2094/MagiCore/download/1.3.2.3"
Downloading "https://spacedock.info/mod/1689/Click%20Through%20Blocker/download/0.1.10.15"
Downloading "https://spacedock.info/mod/1614/ZeroMiniAVC/download/1.1.0.1"
Downloading "https://spacedock.info/mod/1931/ToolbarController/download/0.1.9.4"
Downloading "https://spacedock.info/mod/2210/SpaceTux%20Library/download/0.0.6"
Downloading "https://github.com/KSP-RO/RSSTimeFormatter/releases/download/1.6.1.0/RSSTimeFormatter_1.6.1.0.zip"
Downloading "https://github.com/Starwaster/DeadlyReentry/releases/download/v7.8.0/DeadlyReentry_v7.8.0.zip"
Downloading "https://github.com/KSP-RO/ROEngines/releases/download/v1.7/ROEngines-1.7.zip"
Downloading "https://github.com/KSP-RO/ROTanks/releases/download/v2.3/ROTanks-2.3.zip"
Downloading "https://github.com/KSP-RO/ROCapsules/releases/download/v1.3/ROCapsules-1.3.zip"
Downloading "https://github.com/KSP-RO/ROSolar/releases/download/v1.1.1/ROSolar-1.1.1.zip"
Downloading "https://github.com/shadowmage45/KSPWheel/releases/download/0.16.14.33/KSPWheel-0.16.14.33.zip"
Downloading "https://github.com/TriggerAu/KerbalAlarmClock/releases/download/v3.13.0.0/KerbalAlarmClock_3.13.0.0.zip"
Downloading "https://github.com/KSP-RO/KerbalRenamer/releases/download/v1.4.0/KerbalRenamer_1.4.0.zip"
Downloading "https://github.com/KSP-RO/KSCSwitcher/releases/download/v2.0.0.0/KSCSwitcher_2.0.0.0.zip"
Downloading "https://github.com/Boris-Barboris/AtmosphereAutopilot/releases/download/v1.5.16/AtmosphereAutopilot.zip"
Downloading "https://github.com/KSP-RO/ProceduralFairings/releases/download/v1.8.3/ProceduralFairings-1.8.3.zip"
Downloading "https://github.com/KSP-RO/ProceduralParts/releases/download/v2.1.2/ProceduralParts-2.1.2.zip"
Downloading "https://github.com/m4v/RCSBuildAid/releases/download/v1.0.3/RCSBuildAid_v1.0.3.zip"
Downloading "https://github.com/DRVeyl/RealAntennas/releases/download/v1.3.0/RealAntennas-1.3.0.zip"
Downloading "https://github.com/mwerle/ShipManifest/releases/download/6.0.2.0/ShipManifest-6.0.2.0_20201230085422.zip"
Downloading "https://github.com/KSP-RO/ROKerbalism/releases/download/v1.0/GameData.zip"
Downloading "https://github.com/KSP-RO/TestFlight/releases/download/2.0.0/TestFlight-2.0.0.zip"
Downloading "https://github.com/KSP-RO/RSS-Textures/releases/download/v18.3/16384.zip"
Downloading "https://github.com/KSP-RO/RealismOverhaul/releases/download/v13.0.1/RealismOverhaul-v13.0.1.zip"
Downloading "https://github.com/KSP-RO/AJE/releases/download/v2.16.0/Advanced_Jet_Engine_v2.16.0.zip"
Downloading "https://github.com/dkavolis/Ferram-Aerospace-Research/releases/download/v0.16.0.2_Mader/FAR_0_16_0_2_Mader.zip"
Downloading "https://github.com/KSP-RO/SolverEngines/releases/download/v3.9.0/SolverEngines_v3.9.0.zip"
Downloading "https://github.com/KSP-RO/Kerbal-Joint-Reinforcement-Continued/releases/download/v3.5.2/Kerbal-Joint-Reinforcement_v3.5.2.zip"
Downloading "https://github.com/ChrisViral/RealChute/releases/download/v1.4.8/RealChute_v1.4.8.zip"
Downloading "https://github.com/NathanKell/ModularFuelSystem/releases/download/rf-v12.9.1/RealFuels_v12.9.1.zip"
Downloading "https://github.com/UmbraSpaceIndustries/CommunityResourcePack/releases/download/1.4.2/CRP_1.4.2.0.zip"
Downloading "https://github.com/KSP-RO/RealHeat/releases/download/v5.1/RealHeat_v5.1.zip"
Downloading "https://github.com/KSP-RO/RealPlume/releases/download/v13.3.2/RealPlume_v13.3.2.zip"
Downloading "https://github.com/snjo/Firespitter/releases/download/v7.17/Firespitter_7.17.zip"
Downloading "https://github.com/linuxgurugamer/RetractableLiftingSurface/releases/download/0.2.1.1/RetractableLiftingSurface-1.8.0-0.2.1.1.zip"
Downloading "https://github.com/jrossignol/ContractConfigurator/releases/download/1.30.5/ContractConfigurator_1.30.5.zip"
Downloading "https://github.com/Kerbas-ad-astra/Stock-Revamp/releases/download/v1.15.1/VenStockRevamp-v1.15.1.zip"
Downloading "https://github.com/KSP-RO/RealSolarSystem/releases/download/v18.1.4/RealSolarSystem_v18.1.4.zip"
Downloading "https://github.com/Kopernicus/Kopernicus/releases/download/release-38/Kopernicus-1.11.1-38.zip"
Downloading "https://github.com/DMagic1/DMModuleScienceAnimateGeneric/releases/download/v0.23/DMModuleScienceAnimateGeneric_v0.23.zip"
Downloading "https://github.com/KSP-RO/ROLibrary/releases/download/v1.1.1/ROLib-1.1.1.zip"
Downloading "https://github.com/shadowmage45/TexturesUnlimited/releases/download/1.5.10.25/TexturesUnlimited-1.5.10.25.zip"
Downloading "https://github.com/blowfishpro/B9PartSwitch/releases/download/v2.17.0/B9PartSwitch_v2.17.0.zip"
Downloading "https://github.com/linuxgurugamer/PatchManager/releases/download/0.0.17.2/PatchManager-1.8.0-0.0.17.2.zip"
Downloading "https://github.com/raidernick/BDAnimationModules/releases/download/v0.6.6.0/BDanim_v0.6.6.0.zip"
Downloading "https://github.com/Kerbalism/Kerbalism/releases/download/3.13/Kerbalism-Core_v3.13_for_KSP1.8.0-1.11.9.zip"
Downloading "https://github.com/KSPModdingLibs/HarmonyKSP/releases/download/2.0.4.0/HarmonyKSP_2.0.4.0_for_KSP1.8%2B.zip"
Trying to install RP-0 v1.8.1, but it's not downloaded or download is corrupted
Error during installation!
```

**Comment by jwvanderbeck** [comment] 2021-05-09 23:00
Confirmed by trying to install JUST Harmony 2 and get the same error

**Comment by DasSkelett** [comment] 2021-05-09 23:05
This probably affects every mod you try to download, Harmony is just a red herring there. The URL is fine, it's simply escaped.
If you look closely, it's failing when installing the first mod of the set (which is also the first mod that is downloaded if it isn't cached, e.g. RP-0).

For me this looks like another case of https://github.com/KSP-CKAN/CKAN/issues/3355

@jwvanderbeck, did you change the cache location of CKAN after starting it, and not restart since? That would explain the issue. You should be able to fix it by simply restarting CKAN once (and whenever you change the cache location), until we have a new release out that includes the fix.

**Comment by jwvanderbeck** [comment] 2021-05-09 23:06
I'm guessing the problem is the URL? Does CKAN have issues with the URLEncoding maybe? `https://github.com/KSPModdingLibs/HarmonyKSP/releases/download/2.0.4.0/HarmonyKSP_2.0.4.0_for_KSP1.8%2B.zip`

Just manually went to the URL and it worked.  Not sure why it doesn't in CKAN though.

**Comment by jwvanderbeck** [comment] 2021-05-09 23:06
> This probably affects every mod you try to download, Harmony is just a red herring there. The URL is fine, it's simply escaped.
> If you look closely, it's failing when installing the first mod of the set (which is also the first mod that is downloaded if it isn't cached, e.g. RP-0).
> 
> For me this looks like another case of [KSP-CKAN/CKAN#3355](https://github.com/KSP-CKAN/CKAN/issues/3355)
> 
> @jwvanderbeck, did you change the cache location of CKAN after starting it, and not restart since? That would explain the issue. You should be able to fix it by simply restarting CKAN once (and whenever you change the cache location), until we have a new release out that includes the fix.

Ah interesting! Yes actually I did.  So totally unrelated error :)

**Comment by HebaruSan** [comment] 2021-05-09 23:08
Duplicate of #3355

**Comment by HebaruSan** [comment] 2021-05-09 23:08
Thanks for reporting. This should be fixed in the next release based on changes we worked on recently.

**Closed by HebaruSan** 2021-05-09 23:08 UTC
Labels: Duplicate
