### ISSUE TITLE
Netkan should support multiple licences, as per the CKAN spec.

### ISSUE THREAD

**Issue by politas** [KSP-CKAN/NetKAN#1424] opened 2015-05-26 12:12 UTC
It has come to my attention that the CKAN spec allows multiple licences to be listed, yet we are "choosing the most restrictive" when adding mods, rather than listing all utilised by mod authors. 

I believe this is a faulty idea, for two reasons:

1) If a mod author releases under multiple licences, users have the right to use whichever license they want for redistribution purposes.

2) As per [this advice] (http://forum.kerbalspaceprogram.com/threads/44738) to mod authors, different elements of a mod may be licensed under different licences. GPL makes sense for code, while CC makes sense for artwork, but some licence terms of each are inappropriate when applied to the reverse, so it may be legally inaccurate to assign a single licence.

**Comment by politas** [comment] 2015-05-26 12:16
It seems we currently can't just start adding all the licences. (see #1419)

**Comment by Dazpoet** [comment] 2015-05-26 12:17
I'd call this a duplicate of https://github.com/KSP-CKAN/CKAN/issues/22 and would very much like to see this argumentation added to that issue since something like this should live in the CKAN repository rather than here.

On the topic at hand I very much agree that this is an important subject and should be fixed since we currently use a subpar method of handling the situation. This should also be _extremely_ relevant to https://github.com/KSP-CKAN/CKAN/issues/935

**Comment by politas** [comment] 2015-05-26 12:18
Can you remove that tag, since I've now focused this on updating NetKAN?

**Comment by Dazpoet** [comment] 2015-05-26 12:24
Well I can remove it by this repository is still only for .netkan files and development of netkan.exe should rather live in https://github.com/KSP-CKAN/CKAN-netkan. However https://github.com/KSP-CKAN/CKAN/issues/852 and the future re-integration of CKAN-netkan into the CKAN repo will make CKAN the best place by far.

Note: I'm not trying to kill this issue in any way, I think this is of the outmost importance and it would make my life *so* much easier! I'm just trying to get it into the right place :)

**Comment by politas** [comment] 2015-05-26 12:32
Really? It seemed obvious to me that development of the NetKAN program would be in this repository, but ok. Shall I copy the original post into a new issue in https://github.com/KSP-CKAN/CKAN?

**Comment by Dazpoet** [comment] 2015-05-26 12:46
Aye it's a huge list, which is why some of them are getting merged together :)

I'd acctually recommend adding to and expanding further in https://github.com/KSP-CKAN/CKAN/issues/22 rather than raising a new issue. Although that issue is about adding different licenses to different parts of a mod based on sorting the addition of multiple licenses to a whole mod should be a simple sub-set of that. We would just add information of multiple licenses and then sort the entire mod-directory into each license.

**Comment by politas** [comment] 2015-05-26 13:10
Ok, I've expanded my comment on KSP-CKAN/CKAN#22 and am now happy for this to marked as a duplicate.

**Comment by plague006** [comment] 2015-07-12 12:23
Closing this in favor of KSP-CKAN/CKAN#22.

**Closed by plague006** 2015-07-12 12:23 UTC
Labels: Duplicate
