### ISSUE TITLE
[Bug] Error installing newest Kopernicus

### ISSUE THREAD

**Issue by zheskett** [KSP-CKAN/NetKAN#9498] opened 2022-12-27 04:11 UTC
Background
----------
* Operating System: Windows 11
* CKAN Version: 1.31.2
* KSP Version: 1.12.4

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
Downloading Kopernicus, if you install the newest version, there is an error with the zip file that prevents it from being downloaded.

**Steps to reproduce**
* Go to Kopernicus
* Click on Install
* See error during installation

**Expected behavior**

It should download and install like normal

**CKAN error code (if applicable):**

```
CKAN.InvalidModuleFileKraken: Kopernicus 2:release-1.12.1-139: C:\Users\zhesk\AppData\Local\CKAN\downloads\downloading\41C4F207-Kopernicus-2-release-1.12.1-139.zip has length 1077014, should be 1074657
   at CKAN.NetModuleCache.Store(CkanModule module, String path, IProgress`1 progress, String description, Boolean move)
   at CKAN.NetAsyncModulesDownloader.ModuleDownloadComplete(Uri url, String filename, Exception error, String etag)
```

**Comment by HebaruSan** [comment] 2022-12-27 04:24
See Kopernicus/Kopernicus#553, the download was replaced by the mod maintainer. Click Refresh in CKAN to update your metadata.

**Comment by HebaruSan** [comment] 2022-12-27 04:24
Duplicate of #9461

**Closed by HebaruSan** 2022-12-27 04:24 UTC
