### ISSUE TITLE
KerbalStuffBot failed travis builds

### ISSUE THREAD

**Issue by SirCmpwn** [KSP-CKAN/NetKAN#546] opened 2015-01-21 07:08 UTC
Recent pull requests made by the bot are failing the travis build. What is it doing wrong?

**Comment by Ippo343** [comment] 2015-01-29 21:48
I'm checking and it seems that most of them are caused by invalid licenses.
Others are more misterious, Jenkins doesn't report any cause for those...

**Comment by TeddyDD** [comment] 2015-02-08 12:48
I don't know how adding mods to KerbalStuff works but maybe adding some kind of drop-down menu with common licences (in valid format :wink: ) to choose from would help? Of course this is Kerbal Stuff related request ;)

**Comment by hakan42** [comment] 2015-02-08 13:43
Yes, the problem is usually with the mods for which the author chose a the "other" option an then typed in a license string unknown to us in the free-form field that appears

**Comment by jwvanderbeck** [comment] 2015-02-08 16:24
Wanted to add to this that there is a checkbox when you add your mod to KerbalStuff that says if you want to add it to CKAN as well.  I UNCHEKCED this and KerbalStuff still submitted a PR here for my mod :(

**Comment by hakan42** [comment] 2015-02-08 16:38
Yep, but this is now something that has been go to the kerbalstuff repo. I even believe there is an open ticket for that over there.

**Comment by politas** [comment] 2015-05-19 03:53
It's also terrible for mods that need install or depends directives, it seems to me.

**Comment by politas** [comment] 2015-05-19 04:00
I think a lot of Mod Authors don't really understand software licensing. They rarely include the license text in their download, which makes it really hard to know which license they mean when they say "MIT", for instance. Found one that had a license called "CC BY-SA-NC", which I assume meant "CC-BY-NC-SA".

**Comment by Dazpoet** [comment] 2015-05-25 22:23
Quick glance over in the KS repo made me find https://github.com/KerbalStuff/KerbalStuff/issues/98 which is a better tracker of this issue so I'll close this.

**Closed by Dazpoet** 2015-05-25 22:23 UTC
