### ISSUE TITLE
[Bug] RealPlume and RealPlume Stock Config Dependency Issue Persistence

### ISSUE THREAD

**Issue by Retr0r0cket** [KSP-CKAN/NetKAN#8626] opened 2021-07-05 22:19 UTC
Background
----------
* Operating System: Windows 10 20H2
* CKAN Version: 1.30.4
* KSP Version: 1.12.1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

Yes

Problem
-------
**Describe the bug**

RealPlume says RealPlume Stock Configs are a dependency which isn't up to date so you can't download either and the same happens in reverse (i.e. try to download Stock Configs, says RealPlume is out of date). This is despite both being listed to support any version of 1.12. Was not fixed earlier when previously addressed by changing module manager version compatability.

**Steps to reproduce**
Click on box to install either RealPlume or RealPlume stock configs
See error message

**Expected behavior**
Will say, "RealPlume 2:v13.3.2 depends on RealPlumeConfigs, which is not compatible with the currently installed game version" or, " RealPlumeConfigs depends on RealPlume 2:v13.3.2, which is not compatible with the currently installed game version."

**Screenshots (if applicable)**

![image](https://user-images.githubusercontent.com/76929081/124521346-0bf65480-dda4-11eb-8cbb-fb6621aa1e8d.png)
![image](https://user-images.githubusercontent.com/76929081/124521366-19134380-dda4-11eb-8d82-e896be229824.png)
![image](https://user-images.githubusercontent.com/76929081/124521443-58419480-dda4-11eb-8aff-de8d2d312dc8.png)

**Comment by DasSkelett** [comment] 2021-07-05 22:29
Duplicate of #8618

**Comment by DasSkelett** [comment] 2021-07-05 22:29
Please don't open a new issue for the same problem, we can reopen the existing one if it still persists.

**Closed by DasSkelett** 2021-07-05 22:29 UTC
