### ISSUE TITLE
NetKAN KerbalStuff funny versions.

### ISSUE THREAD

**Issue by qm3ster** [KSP-CKAN/NetKAN#2354] opened 2015-09-29 08:34 UTC
KerbalStuff changelog tab:
```
Version 1.9g for Kerbal Space Program 1.0.4 <- This is what download button gives.
Released on 2015-09-10

Version Beta_1.9f for Kerbal Space Program 1.0.4
Released on 2015-08-24

Version Beta_19.b for Kerbal Space Program 1.0.4 <- This is what NetKAN currently indexes.
Released on 2015-08-10
```
I imagine this behavior is wrong, both because dates and because download button.
(Yes, I know the names are quite a bit funny, but as you see they are getting better, not worse over time.)
In the meantime, how do I fix it with epochs, documentation is not explicit enough for me.

**Comment by plague006** [comment] 2015-09-29 17:47
The behaviour is correct if you think of it like a computer. Beta_"19" > Beta_"1.9"
19 > 1
This is an error in the mod author's versioning scheme.

It happens often enough that we have a specific netkan option for this case, and it's `x_netkan_epoch`. Thanks for bringing this to my attention, it'll be addressed in #2355

**Closed by plague006** 2015-09-29 17:47 UTC

**Comment by qm3ster** [comment] 2015-09-29 21:16
Yes, but other than manually fixing it after errors are discovered, it could just parse the publishing dates on KerbalStuff.

**Comment by plague006** [comment] 2015-09-29 21:34
It could parse dates until the cows come home, the issue is that machines look at version numbers to order things. We can't outright replace version numbers with release dates. For a more thorough look at the issue see https://github.com/KSP-CKAN/CKAN/issues/963
