### ISSUE TITLE
[Bug] Upon trying to install new mod, it flags a conflict within a mod I already had installed which was working fine.

### ISSUE THREAD

**Issue by OnyxOnix** [KSP-CKAN/NetKAN#9088] opened 2022-04-24 17:53 UTC
Background
----------
* Operating System: Windows 11
* CKAN Version: v1.30.4
* KSP Version: 1.12.3.3173

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
When attempting to install (seemingly) any new mod, it errors with the following message: 

* Scatterer 3:v0.0834 conflicts with Scatterer

I already had Scatterer installed as a dependency for the Astronomer's Visual Pack. The mods I tried to install this time were Procedural Parts and B9 Aerospace (procedural) Wings, so are seemingly irrelevant. It seems it's flagging a conflict within a mod I already have working just fine.

**Steps to reproduce**
I guess install AVP as above, then install something else? I'm not sure. It seemed okay until today.

**Expected behavior**
It to work. No conflict was noted between the new mods and Scatterer, and the error is flagging a different conflict regardless.

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment] 2022-04-24 18:13
Duplicate of #8866

**Comment by HebaruSan** [comment] 2022-04-24 18:14
See KSP-CKAN/CKAN#3479 for details and workaround (rename your lowercase `scatterer` folder in GameData to sentence-case `Scatterer).

**Closed by HebaruSan** 2022-04-24 18:14 UTC
Labels: Support, Duplicate
