### ISSUE TITLE
Ven's Stock Revamp Resurrected

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#7499] opened 2019-11-15 17:12 UTC
Per this thread:
https://forum.kerbalspaceprogram.com/index.php?/topic/189732-18x-vens-stock-revamp-resurrected-v1141-mercury-delayed-12-nov-02019/&tab=comments#comment-3705563

this needs to be added.  however, there are two current versions, one for regular and one for RO, the one for RO has an earlier version number.  Maybe doing a manual one first for the RO and then a more automatic one for the regular one would be it, but this is beyond what I'm comfortable doing

**Comment by DasSkelett** [comment] 2019-11-15 17:19
@Kerbas-ad-astra already opened a issue: #7498

**Comment by HebaruSan** [comment] 2019-11-15 17:19
Duplicate of #7498

**Closed by DasSkelett** 2019-11-15 17:19 UTC
Labels: Mod-request
