### ISSUE TITLE
for 161, CKAN GUI refuses to recognise number of mods exported from 151

### ISSUE THREAD

**Issue by andersenman** [KSP-CKAN/NetKAN#6943] opened 2019-01-13 11:52 UTC
On a clean and new installation of KSP 1.6.1+MH expansion, I am trying to install a number of mods exported from a KSP 1.5.1 installation. For 1.5.1 I set 1.5, 1.4, and 1.3 as compatible. For 1.6.1, the versions 1.6, 1.5, 1.4, and 1.3 are set as compatible.
However, the majority of mods are ignored, and only about 17 of 44 mods are installed in 1.6.1, and I have not been able to find a discernible pattern which ones are installed and which ones aren't.

Background
----------

**CKAN Version:** 
1.25.4

**KSP Version: ** 
´1.5.1.2335 and 1.6.1.2401

**Operating System:** 
Win 7 64-bit

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
I do not think so, but if at all, it would have been tweaked cfgs

**Affected mods and mod versions:**
Please consult attached screenshots and ckan files.
(With all due respect, if you request data that easily comes in lists with several dozens of entries, please provide means to automate generation of such a list.)

Problem
-------

**What steps did you take in CKAN?**
with the modlist for ksp151 loaded, exported the .ckan file
created a new entry for ksp161 and activated it
set compatible versions from 1.6 to 1.6, 1.5, 1.4, and 1.3
attempted to install from .ckan and loaded the file above, hit Apply Changes

**What did you expect to happen?**
Installation of all mods listed in .ckan file

**What happened instead?**
Installation of a seemingly random selection.

**Screenshots:**
![151](https://user-images.githubusercontent.com/17570115/51084913-3ebeb500-1732-11e9-8920-f712c63af76c.png)
![161](https://user-images.githubusercontent.com/17570115/51084914-3ebeb500-1732-11e9-8ca0-fa75da0b530c.png)

[151.ckan.txt](https://github.com/KSP-CKAN/NetKAN/files/2753032/151.ckan.txt)
[161.ckan.txt](https://github.com/KSP-CKAN/NetKAN/files/2753033/161.ckan.txt)

**CKAN error codes (if applicable):** 
none

**Comment by DasSkelett** [comment] 2019-01-13 12:41
Thanks for the detailed report!
This seems like a duplicate of https://github.com/KSP-CKAN/CKAN/issues/2652 and will be fixed in https://github.com/KSP-CKAN/CKAN/pull/2653.
Until then, you can try one of the workarounds of [this comment](https://github.com/KSP-CKAN/CKAN/issues/2652#issuecomment-453230609).

**Comment by HebaruSan** [comment] 2019-01-13 16:34
Confirmed duplicate.

**Closed by HebaruSan** 2019-01-13 16:34 UTC
