### ISSUE TITLE
[Bug]: Errors unzipping Extraplanetary Launchpads

### ISSUE THREAD

**Issue by diabetocles** [KSP-CKAN/NetKAN#9728] opened 2023-07-14 17:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 10

### CKAN Version

Latest 1.32.0

### Game Version

1.12.5.3190

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

Other than manually installed mods no. Also removed manually installed mods and tested with same results.

### Describe the bug

Upon ckan installing EL it has an error unzipping see below.

**Error message**
CKAN.InvalidModuleFileKraken: ExtraPlanetaryLaunchpads 6.99.3.0: C:\Users\redacted\AppData\Local\CKAN\downloads\downloading\5E0A4EB7-ExtraPlanetaryLaunchpads-6.99.3.0.zip is not a valid ZIP file: Error in step EntryData for ExtraplanetaryLaunchpads/Parts/LandingPad/LandingPad.mu: Exception during test - 'Unknown block type 6'
   at CKAN.NetModuleCache.Store(CkanModule module, String path, IProgress`1 progress, String description, Boolean move, CancellationToken cancelToken)
   at CKAN.NetAsyncModulesDownloader.ModuleDownloadComplete(Uri url, String filename, Exception error, String etag)

**CKAN output**
About to install:

 * Extraplanetary Launchpads 6.99.3.0 (taniwha.org, 16.1 MiB)
Downloading "http://taniwha.org/~bill/ExtraplanetaryLaunchpads_v6.99.3.zip"
Finished downloading ExtraPlanetaryLaunchpads 6.99.3.0, validating and storing to cache...
Trying to install ExtraPlanetaryLaunchpads 6.99.3.0, but it's not downloaded or download is corrupted
Error during installation!
If the above message indicates a download error, please try again. Otherwise, please open an issue for us to investigate.
If you suspect a metadata problem: https://github.com/KSP-CKAN/NetKAN/issues/new/choose
If you suspect a bug in the client: https://github.com/KSP-CKAN/CKAN/issues/new/choose

### Steps to reproduce

Install Extraplanetary launchpad from ckan interface.

### Relevant log output

```shell
**Error message**
CKAN.InvalidModuleFileKraken: ExtraPlanetaryLaunchpads 6.99.3.0: C:\Users\redacted\AppData\Local\CKAN\downloads\downloading\5E0A4EB7-ExtraPlanetaryLaunchpads-6.99.3.0.zip is not a valid ZIP file: Error in step EntryData for ExtraplanetaryLaunchpads/Parts/LandingPad/LandingPad.mu: Exception during test - 'Unknown block type 6'
   at CKAN.NetModuleCache.Store(CkanModule module, String path, IProgress`1 progress, String description, Boolean move, CancellationToken cancelToken)
   at CKAN.NetAsyncModulesDownloader.ModuleDownloadComplete(Uri url, String filename, Exception error, String etag)

**CKAN output**
About to install:

 * Extraplanetary Launchpads 6.99.3.0 (taniwha.org, 16.1 MiB)
Downloading "http://taniwha.org/~bill/ExtraplanetaryLaunchpads_v6.99.3.zip"
Finished downloading ExtraPlanetaryLaunchpads 6.99.3.0, validating and storing to cache...
Trying to install ExtraPlanetaryLaunchpads 6.99.3.0, but it's not downloaded or download is corrupted
Error during installation!
If the above message indicates a download error, please try again. Otherwise, please open an issue for us to investigate.
If you suspect a metadata problem: https://github.com/KSP-CKAN/NetKAN/issues/new/choose
If you suspect a bug in the client: https://github.com/KSP-CKAN/CKAN/issues/new/choose
```

**Comment by HebaruSan** [comment] 2023-07-14 17:09
That mod's host is broken and has been so for quite a while, unfortunately. See taniwha/Extraplanetary-Launchpads#202 and taniwha/Extraplanetary-Launchpads#205.

**Comment by HebaruSan** [comment] 2023-07-14 17:09
Duplicate of #9578

**Closed by HebaruSan** 2023-07-14 17:09 UTC
