### ISSUE TITLE
[Mod] TU Recolors (Stock, 

### ISSUE THREAD

**Issue by oofergoofer** [KSP-CKAN/NetKAN#9390] opened 2022-10-21 15:15 UTC
Mod info
--------
* Mod name: Textures Unlimited Recolour Depot
* Author(s): Manwith Noname,
* License: CC BY NC SA
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/174188-112x-textures-unlimited-recolour-depot/
* Download: Listed in forum post

**Comment by HebaruSan** [comment] 2022-10-21 16:36
Duplicate of #7961, closed because the download links are on Google Drive, which doesn't work with CKAN. Checking now, this still seems to be the case. There was a chat with the author at that time:

- https://forum.kerbalspaceprogram.com/index.php?/topic/174188-112x-textures-unlimited-recolour-depot/&do=findComment&comment=4037909
- https://forum.kerbalspaceprogram.com/index.php?/topic/174188-112x-textures-unlimited-recolour-depot/&do=findComment&comment=4039120
- https://forum.kerbalspaceprogram.com/index.php?/topic/174188-112x-textures-unlimited-recolour-depot/&do=findComment&comment=4040149

**Closed by HebaruSan** 2022-10-21 16:36 UTC
Labels: Mod-request, Blocked-on-Other, Needs looking into, Duplicate

**Comment by oofergoofer** [comment] 2022-10-21 16:45
alright, thanks for the response, have a nice day

**Comment by HebaruSan** [comment] 2022-10-21 16:46
Oops, I'm sorry I was so terse about that. Thanks for contacting us, it's always helpful to hear about requests for mods, and you could not have been expected to know about that previous exchange. Cheers, and here's hoping there's a shift in this mod's hosting in the future!

**Comment by oofergoofer** [comment] 2022-10-21 16:49
i didn't mean to be rude or anything, that's just my way of typing lol, anyways thanks for the response, bye
