### ISSUE TITLE
Error updating Phoenix Industries Cargo Resupply System

### ISSUE THREAD

**Issue by bombaatu** [KSP-CKAN/NetKAN#5253] opened 2017-02-10 07:25 UTC
File           : GameData/CTN/Agencies/Agents.cfg
Installing Mod : PhoenixIndustriesCargoResupplySystem v2.2
Owning Mod     : PhoenixIndustriesBoosters
CKAN Version   : v1.22.1-0-g174271a (beta)

The CTN/Agencies/Agents.cfg file was installed by CKAN with another Phoenix Industies mod

**Comment by linuxgurugamer** [comment] 2017-02-10 19:17
Duplicate of: #5216

**Closed by linuxgurugamer** 2017-02-10 19:17 UTC
