### ISSUE TITLE
[Bug] today i oppened ckan and the language ramdomly change to chinese. how do i change it back to english?

### ISSUE THREAD

**Issue by aytitien2005** [KSP-CKAN/NetKAN#8774] opened 2021-09-22 13:07 UTC
Background
----------
* Operating System: 
* CKAN Version: 
* KSP Version: 

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

Problem
-------
**Describe the bug**

**Steps to reproduce**
* Go to...
* Click on...
* See error

**Expected behavior**

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment] 2021-09-22 14:54
Duplicate of KSP-CKAN/CKAN#3244.

**Closed by HebaruSan** 2021-09-22 14:54 UTC
