### ISSUE TITLE
[Bug] Problem with Modular Flight Integrator

### ISSUE THREAD

**Issue by stonewolfpc** [KSP-CKAN/NetKAN#8245] opened 2020-11-29 20:22 UTC
Background
----------
* Operating System: 
Windows 10 Pro x64
* CKAN Version: 
1.29.0
* KSP Version: 
1.10.1.2939

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

Problem
-------
**Describe the bug**
When trying to install Modular Flight Integrator it says it's not compatible, then it stops me from being able to do it manually.  Then when I try to upgrade a mod, it gives me an error and says continue or quit.  If I continue it won't let me do anything in terms of downloading etc.  Ferram Aerospace Research, as well as Kepernicus Bleeding Edge 1.10.1 need it, and won't update without it.  I tried first to install Kepernicus without it, but it says it's required.  Now when I try to install them both they conflict.  GRRR!

**Steps to reproduce**
* Go to...
All tab, type in the search bar Modular Flight and then try to install it for 1.10.1.  It offers to let you install in a pop up but nothing happens.  Then go to the update tab, try to update Ferram Aerospace or Kepernicus Bleeding Edge, and an error occurs.

* Click on...
* See error

```
************** Exception Text **************
CKAN.ModuleIsDLCKraken: Exception of type 'CKAN.ModuleIsDLCKraken' was thrown.
   at CKAN.RelationshipResolver.Add(CkanModule module, SelectionReason reason)
   at CKAN.RelationshipResolver.AddModulesToInstall(IEnumerable`1 modules)
   at CKAN.ModList.ComputeConflictsFromModList(IRegistryQuerier registry, IEnumerable`1 change_set, KspVersionCriteria ksp_version)
   at CKAN.ManageMods.<UpdateChangeSetAndConflicts>d__117.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at CKAN.ManageMods.<ModList_CellValueChanged>d__73.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
```

**Comment by HebaruSan** [comment] 2020-11-29 20:48
> All tab, type in the search bar Modular Flight and then try to install it for 1.10.1. It offers to let you install in a pop up but nothing happens

When I try this, the steps fail to reproduce at this point. I don't see anything resembling "It offers to let you install in a pop up", instead it just installs:

![image](https://user-images.githubusercontent.com/1559108/100553189-fc34f180-3251-11eb-8bc1-98c2549c41b8.png)

Please supply more details about exactly what you're doing.

**Comment by HebaruSan** [comment] 2020-11-29 20:51
Guessing this is a duplicate of #3193, since it mentions MFI and Kop-BE.
Try uninstalling Kop-BE, then click Refresh, then install Kop-BE again.

**Closed** 2020-12-10 04:56 UTC
Labels: Needs more info, Support
