### ISSUE TITLE
TweakScale bug?

### ISSUE THREAD

**Issue by raziel420** [KSP-CKAN/NetKAN#8600] opened 2021-06-27 17:53 UTC
CKAN.InvalidModuleFileKraken: TweakScale v2.4.5.1: C:\Users\bryan\AppData\Local\Temp\tmp96DC.tmp has length 288150, should be 256221
   at CKAN.NetModuleCache.Store(CkanModule module, String path, String description, Boolean move)
   at CKAN.NetAsyncModulesDownloader.ModuleDownloadComplete(Uri url, String filename, Exception error)

**Comment by DasSkelett** [comment] 2021-06-27 17:57
Duplicate of #8598

**Closed by DasSkelett** 2021-06-27 17:57 UTC

**Comment by DasSkelett** [comment] 2021-06-27 18:04
Thanks for the report @raziel420. We're working on it, and with some luck the metadata should be fixed in a few minutes. You can follow #8598 for updates.
