### ISSUE TITLE
Stock Visual Enhancements CKAN upload is completely broken

### ISSUE THREAD

**Issue by UsernameIsTakenAlready** [KSP-CKAN/NetKAN#6107] opened 2017-12-23 22:53 UTC
Installing the Stock Visual Enhancements suite from CKAN results in the following: planets being completely black from orbit/map view/tracking station, invisible water, and broken scatterer config usage

**Comment by HebaruSan** [comment] 2017-12-23 23:18
Thanks for the report!
Is CKAN actually installing something incorrectly here? The install instructions for SVE are:

1. Install the SVE folder to GameData
2. Install SVE-Textures
3. Install EVE without the configs
4. Install Scatterer
5. Install ModuleManager

Those steps are all faithfully translated into the CKAN metadata as far as I can tell:

- https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/StockVisualEnhancements.netkan

Is there a particular file or folder that you noticed was out of place?

**Comment by HebaruSan** [comment] 2017-12-23 23:49
I have just installed SVE with CKAN, and the planets are not black in the tracking station:

![SVE](https://steamuserimages-a.akamaihd.net/ugc/916911912432184761/AD9B34DC5BAA144D29A3A32B37FE268C436728F0/)

We'll need more information to help.

**Comment by HebaruSan** [comment] 2017-12-24 00:15
The above results are the same with Cmdline and ConsoleUI; I'll try GUI next. I've requested input from the [forum thread](https://forum.kerbalspaceprogram.com/index.php?/topic/143288-ksp-131-stock-visual-enhancements-v1280-21-dec-2017/&do=findComment&comment=3251459), so hopefully a flood of useful feedback will be arriving presently.

**Comment by politas** [comment] 2017-12-24 19:04
Black planets usually means multiple EVE configurations. @UsernameIsTakenAlready , have you manually installed any beautification mods, such as Renaissance?

**Comment by HebaruSan** [comment] 2018-01-14 03:35
1. Doesn't seem to be completely broken
2. We have a suggestion for the cause
3. No reply from OP

Closing.

**Closed by HebaruSan** 2018-01-14 03:35 UTC
Labels: Needs more info, Support
