### ISSUE TITLE
Phoenix industries Mods cannot be installed together because of overwrite issues.

### ISSUE THREAD

**Issue by ProwlerProwl** [KSP-CKAN/NetKAN#5192] opened 2017-01-22 14:17 UTC
About to install...

 * Phoenix Industries - Boosters 2.1
 * Phoenix Industries - CubeSat 2.2(cached)

Downloading "https://spacedock.info/mod/246/Phoenix Industries - Boosters/download/2.1"

Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/NetKAN/issues/new

Please including the following information in your report:

File           : GameData/CTN/Agencies/Agents.cfg
Installing Mod : PhoenixIndustriesBoosters 2.1
Owning Mod     : PhoenixIndustriesCargoResupplySystem
CKAN Version   : v1.22.1-0-g174271a (beta)

Your GameData has been returned to its original state.

Error!

**Comment by linuxgurugamer** [comment] 2017-02-10 19:19
Duplicate of #5216

**Closed by linuxgurugamer** 2017-02-10 19:19 UTC
