### ISSUE TITLE
uninstalling mods

### ISSUE THREAD

**Issue by dieless** [KSP-CKAN/NetKAN#6600] opened 2018-06-18 18:46 UTC
After I have installed a mod for KSP, it shows this in the installed listing;
![ckan_cap](https://user-images.githubusercontent.com/40368352/41555356-776b63fc-7305-11e8-93a9-d146df8d5cfb.PNG)

After the mod has been installed the loader shows the AD instead of the checkbox and I have to go to 
C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\GameData
and manually uninstall the mod files, it also fails to recognize mods already there, here are the captures of the two folders if that helps.

![capturekspfolder](https://user-images.githubusercontent.com/40368352/41555547-133d248c-7306-11e8-9d90-d314b2348796.PNG)
![captureksp_gamedata_folder](https://user-images.githubusercontent.com/40368352/41555557-17fba2f0-7306-11e8-95da-4726d28b2e8a.PNG)
Thank you for your time and help.

**Comment by HebaruSan** [comment] 2018-06-18 20:28
Did you install those mods manually or via CKAN?

**Comment by HebaruSan** [comment] 2018-06-19 16:02
Possibly a duplicate of KSP-CKAN/CKAN#2262.

**Closed** 2018-06-27 00:00 UTC
Labels: Support
