### ISSUE TITLE
1094.netkan

### ISSUE THREAD

**Issue by Johnnypoiro** [KSP-CKAN/NetKAN#2139] opened 2015-08-19 20:07 UTC
{
    "spec_version" : 1,
    "identifier"   : "valVisor",
    "$kref"        : "#/ckan/kerbalstuff/1094",
    "x_netkan_license_ok": true
}

**Comment by plague006** [comment] 2015-08-19 23:44
Duplicate of #2138

**Closed by plague006** 2015-08-19 23:44 UTC
