### ISSUE TITLE
Error while installing any mod

### ISSUE THREAD

**Issue by L3eC** [KSP-CKAN/NetKAN#9073] opened 2022-04-16 18:27 UTC
Background
----------
* Operating System: Windows 10 
* CKAN Version: 1.30.4
* KSP Version: 1.12.3.3173

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
Yes

Problem
-------
**Describe the bug**
When I try to install anything, this message pops up:
The following inconsistencies were found:
* Scatterer 3:v0.0825b conflicts with Scatterer
Error during installation!

**Screenshots (if applicable)**

![Screenshot (8)](https://user-images.githubusercontent.com/103331501/163687067-9200f7a6-c8a3-4423-bd30-988b6cb9c9d9.png)

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment] 2022-04-16 18:37
See KSP-CKAN/CKAN#3479 for details and workaround (rename your `scatterer` folder to `Scatterer`).

**Comment by HebaruSan** [comment] 2022-04-16 18:37
Duplicate of #8866

**Closed by HebaruSan** 2022-04-16 18:37 UTC
Labels: Duplicate
