### ISSUE TITLE
RN soviet rockets problem

### ISSUE THREAD

**Issue by raidernick** [KSP-CKAN/NetKAN#3856] opened 2016-05-01 19:46 UTC
I've gotten complaints from several people about problems with my mod and FAR  and/or RSS/RO where when they are all installed through CKAN it causes the vernier engines on my R7 to produce no thrust, making the TWR 0.6 and thus the rocket is unable to liftoff. I have tried replicating this myself and cannot get it to happen. Enough people have complained where I can assume it is an actual issue. I have looked over the netkan files and see no obvious errors.

These people have found that if they make a clean install with the mods manually instead of ckan the issue does no occur, so it is that something is being installed incorrectly or is being corrupted.

I would appreciate another set of eyes to help with this as I am at a loss. 

Page 17-18 of my thread explain the issues and solutions, I have also received several pms from members with the same issue and when I told them to do it manually they stated that fixed the issue: http://forum.kerbalspaceprogram.com/index.php?/topic/79433-105-soviet-probes-soviet-rockets-r7soyuzprotonzenit-2-29-16/&page=18

**Comment by plague006** [comment] 2016-05-02 01:04
I could swear I looked into this.. I remember going as far as comparing the MD5 checksums of the mods packaged vs the mods CKAN installs and trying to match versions. I think I determined Klockheed_Martian_Gimbal didn't match any version CKAN indexed?

I'll have to dig around to find the issue, a cursory search didn't bring it up.

**Comment by raidernick** [comment] 2016-05-02 02:00
The mod doesn't use KM gimbal anymore. I got rid of that during the 1.1 pre-release to use the stock ones. I haven't updated the netkan files yet to reflect this but having km install won't matter if no parts use it.
I'll be updating the netkan files soon to remove it though.

**Comment by plague006** [comment] 2016-05-02 02:05
It's proving really hard to find that old issue so I'm just going to start from the beginning. So 2 files don't match MD5 checks between a manual and CKAN install:

````
FAIL	MD5	Firespitter\Plugins\Firespitter.dll
FAIL	MD5	Klockheed_Martian_Gimbal\Plugins\km_Gimbal.dll
````

**Comment by plague006** [comment] 2016-05-02 02:11
Found it: https://github.com/KSP-CKAN/NetKAN/pull/3612

**Comment by raidernick** [comment] 2016-05-02 02:13
Those files have already been fixed though I got the latest firespitter for 1.1.2 from the github and I don't use km gimbal anymore...

**Comment by plague006** [comment] 2016-05-02 02:24
Would it make sense if your mod and `FirespitterCore-v7.1.5` were causing the issue together? Whatever is included in your .zip is working, so all I can really point at are the differences between CKAN and your .zip.

**Comment by raidernick** [comment] 2016-05-02 02:26
I have the latest version from the official firespitter github though...if the ckan version is causing the issue it means it's installing it wrong or the version is not updating for some reason.

**Comment by plague006** [comment] 2016-05-02 02:39
It's the same filename being installed in the same location as what a manual install would be. CKAN users would be on 7.1.5 and not the most recent version because 7.2.0 and up aren't marked compatible with ksp_version 1.0.5.

All I'm getting at is that in the past you used 7.1.4 and now you're using a version above 7.1.5. 7.1.5 of firespitter might be causing the issue. If you have someone who can reproduce the issue would swapping between the 2 versions of that DLL would at least eliminate it as a possibility.

**Comment by raidernick** [comment] 2016-05-02 02:41
I just made a PR for the netkan files, I no longer support less than KSP 1.1.2, so if that was indeed the issue I will let you know if anyone complains after being forced to use the new versions.

**Comment by plague006** [comment] 2016-05-02 02:42
:+1:

**Comment by plague006** [comment] 2016-05-06 14:49
It seems the issue was pinpointed to `ReflectionPlugin`. https://github.com/KSP-CKAN/NetKAN/pull/3938 added a conflict so closing this.

**Closed by plague006** 2016-05-06 14:49 UTC
