### ISSUE TITLE
Distant Object Enhancement Continued v2.0.0.0

### ISSUE THREAD

**Issue by TheDarkBadger** [KSP-CKAN/NetKAN#7495] opened 2019-11-12 23:47 UTC
Forum Thread: https://forum.kerbalspaceprogram.com/index.php?/topic/189759-181-distant-object-enhancement-continued-v2000-12-november-2019/

NetKAN file:
[DistantObject-v2.0.0.0 NetKAN.zip](https://github.com/KSP-CKAN/NetKAN/files/3838711/DistantObject-v2.0.0.0.NetKAN.zip)

**Comment by HebaruSan** [comment] 2019-11-12 23:48
Duplicate of #7494

**Comment by HebaruSan** [comment] 2019-11-12 23:53
We'll take care of this in #7494.

**Closed by HebaruSan** 2019-11-12 23:53 UTC
