### ISSUE TITLE
[Suggestion] Search all for Recommendations

### ISSUE THREAD

**Issue by VasVadum** [KSP-CKAN/NetKAN#6824] opened 2018-11-07 23:27 UTC
**CKAN Version:** 1.25.3

**KSP Version:** 1.5.1.2335

**Operating System:** Windows 10 Severely Outdated
(You can thank Microsoft for that)

**Have you made any manual changes to your GameData folder ?** 
No

Request/Suggestion:
-------

**What do you expect to happen?**
I'd like to see a button added that will search all installed mods and tell you what they all recommend the same way as if you install a mod and it shows a screen of recommendations.  That way, after several updates I can search to see if any new recommendations happened.

**Comment by HebaruSan** [comment] 2018-11-07 23:47
Thanks for the suggestion. I believe this is a duplicate of KSP-CKAN/CKAN#1764. If there are things that aren't covered there, let us know and we can expand that request or re-open this one as needed.

Note that a form of it is available in the main menu of `ckan consoleui` as "Audit Recommendations" from KSP-CKAN/CKAN#2177.

![image](https://user-images.githubusercontent.com/1559108/48168190-41da9680-e2e6-11e8-88e3-4a9e975a941b.png)

**Closed by HebaruSan** 2018-11-07 23:47 UTC
