### ISSUE TITLE
TAC Life Support 11.2 doesn't have a ckan built

### ISSUE THREAD

**Issue by NathanKell** [KSP-CKAN/NetKAN#2830] opened 2015-12-14 03:14 UTC
I don't see anything wrong offhand with the netkan, but there was no ckan built for the latest release....
(it's for 1.0.5, also, the first 1.0.5 build of TACLS)

https://github.com/taraniselsu/TacLifeSupport/releases

**Comment by plague006** [comment] 2015-12-14 03:36
You're right, there's nothing wrong with the netkan. It's pointing at KerbalStuff and the author hasn't released there.

**Comment by plague006** [comment] 2015-12-14 03:40
Using github as a kref will be problematic due to the .version file's compatibility listings:

````
  "KSP_VERSION": {
    "MAJOR": 1,
    "MINOR": 0,
    "PATCH": 5
  },
  "KSP_VERSION_MIN": {
    "MAJOR": 1,
    "MINOR": 0,
    "PATCH": 0
  },
  "KSP_VERSION_MAX": {
    "MAJOR": 1,
    "MINOR": -1,
    "PATCH": -1
  }
````

**Comment by NathanKell** [comment] 2015-12-14 04:20
Ah, and the problem is it should only have the first block?
(I definitely think we should retarget on github, though, for the record)

**Comment by plague006** [comment] 2015-12-14 15:36
I would love to target github, but I don't want to be responsible for manually changing ksp_version compatibility. If I used the mod or even [played the game](http://puu.sh/lVgDE/8137121a6d.jpg) I would be more inclined, but that's not the case.

The issue is specifically the ksp_version_max' minor and patch versions being -1. It results in the metadata having ksp_version_min: 1.0.0 and ksp_version_max: 1. (ksp_version_max: 1 will cause issues).

**Comment by NathanKell** [comment] 2015-12-14 17:46
Pinging @taraniselsu about this, or I can submit a PR to remove those blocks from the .version.

**Comment by NathanKell** [comment] 2015-12-14 19:42
@plague006 I'm also making a temporary manual .ckan so at least it's on the client...
https://github.com/KSP-CKAN/CKAN-meta/pull/899

**Comment by NathanKell** [comment] 2015-12-14 21:15
After review by @Olympic1 we merged that in so people can play with TACLS meanwhile until this gets sorted out. :)

**Comment by plague006** [comment] 2015-12-14 23:47
:+1:

**Comment by Olympic1** [comment] 2015-12-19 00:07
Closing as a new update is released with a working `.version` file

**Closed by Olympic1** 2015-12-19 00:07 UTC
