### ISSUE TITLE
ExperimentTracker updated to 1.3.4.5, meta data not updated

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#6967] opened 2019-01-21 22:54 UTC
I updated the ExperimentTracker to version 1.3.4.5 on Spacedock.
The netkan has the following kref:

`"$kref"        : "#/ckan/spacedock/1858",`

but it hasn't updated yet

**Comment by HebaruSan** [comment] 2019-01-21 22:57
Duplicate of KSP-SpaceDock/SpaceDock#192. Tell SpaceDock to update their config if you want immediate updates.

**Closed by HebaruSan** 2019-01-21 22:57 UTC
