### ISSUE TITLE
Secure TTS channel?

### ISSUE THREAD

**Issue by Devan-Kerman** [KSP-CKAN/NetKAN#6426] opened 2018-04-01 15:04 UTC
Background
----------

**CKAN Version:** 
1.22.6

**KSP Version:** 
1.2.2

**Operating System:** 
Windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
Nope

**Affected mods and mod versions:**

Problem
-------

**What steps did you take in CKAN?**
Launched

**What did you expect to happen?**
it to work?

**What happened instead?**
I pressed dismiss but no mods popped up in the list thingy

**Screenshots:**

![image](https://user-images.githubusercontent.com/28693059/38174520-115d44bc-3594-11e8-9f20-6d5ce1fa231f.png)

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment] 2018-04-01 15:54
Duplicate of KSP-CKAN/CKAN#2293, fixed in KSP-CKAN/CKAN#2297. Install this version:

- https://github.com/KSP-CKAN/CKAN/releases/tag/v1.24.0

**Closed by HebaruSan** 2018-04-01 15:54 UTC
