### ISSUE TITLE
Cand use Github In SCAN

### ISSUE THREAD

**Issue by StendUper** [KSP-CKAN/NetKAN#6301] opened 2018-03-01 13:45 UTC
-->

![image](https://user-images.githubusercontent.com/36959017/36847215-4cc3a05a-1d66-11e8-99f6-4aa459f692d4.png)
![image](https://user-images.githubusercontent.com/36959017/36847424-e54db1f8-1d66-11e8-8b4e-66393a25f845.png)

----------

**CKAN Version:** 1.24.0pre

**KSP Version:** 1.3.1.1891 

**Operating System:** Windows 7 x64

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
Нет не вносил\Not

Problem:   Не получаеться загружать контент с Github вообще, ето касаеться только его при загрузке с spacedock или других все впорядке\Cant download any content from github in Scan

**Comment by HebaruSan** [comment] 2018-03-01 17:45
Try upgrading your version of .NET. Windows 7 comes with 3.5.1 by default, but GitHub now requires 4.5 or later to access their servers.

**Comment by StendUper** [comment] 2018-03-02 20:34
ok will try now.

**Comment by StendUper** [comment] 2018-03-02 20:56
nope its not working,same result

**Comment by HebaruSan** [comment] 2018-03-02 21:27
Oh, sorry! I didn't notice you were still using the PRE version. You'll need this now:
https://github.com/KSP-CKAN/CKAN/releases/tag/v1.24.0
That makes this a duplicate of KSP-CKAN/CKAN#2293.

**Closed by HebaruSan** 2018-03-02 21:27 UTC
Labels: Support
