### ISSUE TITLE
Stockalike Realism Overhaul Parts Pack

### ISSUE THREAD

**Issue by HyperFunOriginal** [KSP-CKAN/NetKAN#7434] opened 2019-10-18 15:32 UTC
Mod info
--------
* Mod name: Stockalike Realism Overhaul Parts Pack
* Author(s): HyperFun
* License: Do whatever you want
* Homepage: https://spacedock.info/mod/2251/Stockalike%20Realism%20Overhaul%20Parts%20Pack
* Download: https://spacedock.info/mod/2251/Stockalike%20Realism%20Overhaul%20Parts%20Pack

**Comment by HebaruSan** [comment] 2019-10-18 15:40
Duplicate of #7433

**Closed by HebaruSan** 2019-10-18 15:40 UTC

**Comment by HyperFunOriginal** [comment] 2019-10-18 16:00
The mod isn't showing up. For CKAN installations, remove step 3 & 4 and ignore physics.cfg file. Thanks a lot!
