### ISSUE TITLE
[Mod]: JFA

### ISSUE THREAD

**Issue by D4RKN3R** [KSP-CKAN/NetKAN#9944] opened 2024-03-02 18:05 UTC
### Mod Name

JFA

### Author(s)

D4RKN3R

### License

MIT

### Homepage link

https://forum.kerbalspaceprogram.com/topic/223852-jfa-jeb-far-away-1125

### Download link

https://spacedock.info/mod/3565/JFA

**Comment by HebaruSan** [comment] 2024-03-02 18:07
Hi @D4RKN3R, thanks for the submission. This is already in progress...

**Comment by HebaruSan** [comment] 2024-03-02 18:07
Duplicate of #9937

**Closed by HebaruSan** 2024-03-02 18:07 UTC
