### ISSUE TITLE
Red X on download/install screen

### ISSUE THREAD

**Issue by samloops** [KSP-CKAN/NetKAN#6677] opened 2018-08-15 13:15 UTC
Background
----------

**CKAN Version:** 
Error found using 1.24.1.deb, 1.25.2.deb and 1.25.2.exe versions 

**KSP Version:** 
Tested against KSP 1.4.5 and KSP 1.3.0

**Operating System:** 
Linux Mint 18.3, i7, 32G, Kernel 4.13.0-25-generic

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
Numerous changes to version KSP 1.3.0, however, CKAN was working with that version until recently.  Same CKAN error found when tested against fresh, unmodded install of KSP 1.4.5

**Affected mods and mod versions:**
Seems to affect virtually all mods, except that on occasion, a mod will install properly, especially if first mod installed.  Subsequent mods seem to fail. 

Problem
-------

**What steps did you take in CKAN?**
CKAN loads, updates repositories and presents Manage mods screen as normal.  Mods may be selected and all continues normally through the selection and Apply changes process, including listing of the Changeset and Recommended Mods.  I then select Continue. CKAN fails.

**What did you expect to happen?**
Normal download and installation of selected mods. 

**What happened instead?**
Continuing from the Recommended Mods screen, I encounter a blank CKAN screen with a red X drawn from corner to corner.  CKAN locks and the process must be killed.

**Screenshots:**

![image](https://user-images.githubusercontent.com/4177130/44149044-74d70502-a04f-11e8-90db-992ad3a748f9.png)

**CKAN error codes (if applicable):** 

Whether starting CKAN from the GUI or a terminal, behavior is identical.  Starting from a terminal yields no messages until the failure.  Then the following terminal messages appear, just as the red X is displayed.  The errors are identical no matter whether calling the Linux version via ./ckan or the Windows .exe is called.

----------------------------------------------
sam@Sam-SSD ~ $ ckan
System.ArgumentOutOfRangeException: ControlCollection does not have that many controls
Parameter name: index
Actual value was 3.
  at System.Windows.Forms.Control+ControlCollection.get_Item (System.Int32 index) [0x00027] in <185f5064526646d192550947861d97b1>:0 
  at System.Windows.Forms.TabControl.GetTab (System.Int32 index) [0x00006] in <185f5064526646d192550947861d97b1>:0 
  at System.Windows.Forms.TabControl.GetTabRect (System.Int32 index) [0x00000] in <185f5064526646d192550947861d97b1>:0 
  at (wrapper remoting-invoke-with-check) System.Windows.Forms.TabControl.GetTabRect(int)
  at System.Windows.Forms.Theming.Default.TabControlPainter.Draw (System.Drawing.Graphics dc, System.Drawing.Rectangle area, System.Windows.Forms.TabControl tab) [0x000df] in <185f5064526646d192550947861d97b1>:0 
  at System.Windows.Forms.ThemeWin32Classic.DrawTabControl (System.Drawing.Graphics dc, System.Drawing.Rectangle area, System.Windows.Forms.TabControl tab) [0x0000a] in <185f5064526646d192550947861d97b1>:0 
  at System.Windows.Forms.TabControl.Draw (System.Drawing.Graphics dc, System.Drawing.Rectangle clip) [0x00005] in <185f5064526646d192550947861d97b1>:0 
  at System.Windows.Forms.TabControl.OnPaintInternal (System.Windows.Forms.PaintEventArgs pe) [0x00017] in <185f5064526646d192550947861d97b1>:0 
  at System.Windows.Forms.Control.WmPaint (System.Windows.Forms.Message& m) [0x0006d] in <185f5064526646d192550947861d97b1>:0 
  at System.Windows.Forms.Control.WndProc (System.Windows.Forms.Message& m) [0x001a4] in <185f5064526646d192550947861d97b1>:0 
  at System.Windows.Forms.TabControl.WndProc (System.Windows.Forms.Message& m) [0x00057] in <185f5064526646d192550947861d97b1>:0 
  at System.Windows.Forms.Control+ControlWindowTarget.OnMessage (System.Windows.Forms.Message& m) [0x00000] in <185f5064526646d192550947861d97b1>:0 
  at System.Windows.Forms.Control+ControlNativeWindow.WndProc (System.Windows.Forms.Message& m) [0x0000b] in <185f5064526646d192550947861d97b1>:0 
  at System.Windows.Forms.NativeWindow.WndProc (System.IntPtr hWnd, System.Windows.Forms.Msg msg, System.IntPtr wParam, 
System.IntPtr lParam) [0x00085] in <185f5064526646d192550947861d97b1>:0 

------------------------------------------------------------
The program hangs at this point.

Currently using Mono 5.14.0.177 with up-to-date certificates.

The only somewhat unusual update to the system was a recent, rare update to Xorg pushed out by Ubuntu / Mint and installed through the normal update process.  No ill-effects noted.

Thanks for your help on this.  I haven't seen any mention of a red X before!

Sam L.

**Comment by HebaruSan** [comment] 2018-08-15 14:52
Duplicate of KSP-CKAN/CKAN#2499.
I think they changed something with threading in Mono recently; this was working for me on Mono 5.10, and then upgrading to 5.14 produced this red X. If you're able to downgrade Mono, that might help.

**Closed by HebaruSan** 2018-08-15 14:52 UTC
