### ISSUE TITLE
[Bug] Scatterer conflicts with Scatterer

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#8868] opened 2021-11-21 12:49 UTC
Background
----------
Windows 10
* CKAN Version: 1.30.4
* KSP Version: 1.12.2

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
no

This is a big career install with JNSQ

Problem
I get the following error when trying to do an update.  Zip file containing the registry attached
[registry.zip](https://github.com/KSP-CKAN/NetKAN/files/7576283/registry.zip)

-------
About to remove:

 * scatterer 3:v0.0825b
The following inconsistencies were found:
* Scatterer 3:v0.0825b conflicts with Scatterer
Error during installation!
If the above message indicates a download error, please try again. Otherwise, please open an issue for us to investigate.
If you suspect a metadata problem: https://github.com/KSP-CKAN/NetKAN/issues/new/choose
If you suspect a bug in the client: https://github.com/KSP-CKAN/CKAN/issues/new/choose

**Comment by linuxgurugamer** [comment] 2021-11-21 12:59
Note:  I have a full copy of the game install at this instance, so if you need/want me to test anything,  I can

**Comment by linuxgurugamer** [comment] 2021-11-21 13:02
Got a similar error when attempting to update another install:

The following inconsistencies were found:
* GPPSecondary 1.6.6.0 conflicts with GPP 1:1.6.6.0
Error during installation!
If the above message indicates a download error, please try again. Otherwise, please open an issue for us to investigate.
If you suspect a metadata problem: https://github.com/KSP-CKAN/NetKAN/issues/new/choose
If you suspect a bug in the client: https://github.com/KSP-CKAN/CKAN/issues/new/choose

**Comment by DasSkelett** [comment] 2021-11-21 13:07
> Scatterer 3:v0.0825b conflicts with Scatterer

Duplicate of #8866
Try the workaround @HebaruSan suggested in his comment: https://github.com/KSP-CKAN/NetKAN/issues/8866#issuecomment-974679218

> GPPSecondary 1.6.6.0 conflicts with GPP 1:1.6.6.0

This is unrelated and intended, GPPSecondary includes GPP:
https://github.com/KSP-CKAN/NetKAN/pull/8804

**Comment by linuxgurugamer** [comment] 2021-11-21 13:12
ok to the GPP (it didn't used to include GPP

**Comment by linuxgurugamer** [comment] 2021-11-21 13:17
@DasSkelett Sorry about the title, I'm actually working right now, got distracted

**Comment by linuxgurugamer** [comment] 2021-11-21 13:21
Regarding the workaround, I just deleted Scatterer and all related and then reinstalled them,

**Comment by DasSkelett** [comment] 2021-11-21 13:37
> Regarding the workaround, I just deleted Scatterer and all related and then reinstalled them,

I take this as a confirmation that everything works again for you? Closing the issue then.
Once you're on the new metadata from #8862, the issue should also be gone for good (but unfortunately the "metadata changed"-reinstall will likely fail for many people).

**Closed by DasSkelett** 2021-11-21 13:37 UTC
Labels: Bug
