### ISSUE TITLE
Throttle Controlled Avionics does not work in 1.9.1

### ISSUE THREAD

**Issue by damerell** [KSP-CKAN/NetKAN#8140] opened 2020-09-11 13:49 UTC
I cannot get KSP 1.9.1 to load with TCA installed via CKAN, no matter what other mods are installed.

**Comment by DasSkelett** [comment] 2020-09-11 13:54
What version of TCA did CKAN install for you? (You can check that in the "Versions" tab on the right)
Did you try to install the same version manually too? If yes, did it work then? If no, could you try that?

Did KSP not load at all? Did it show an error? Or did it load, but TCA didn't show up?

**Comment by damerell** [comment] 2020-09-11 14:07
I'll have to answer the other questions when I get home, but it didn't load at all - started, but just pauses indefinitely midway through the loading process, apparently while parsing some other part.

**Comment by HebaruSan** [comment] 2020-09-11 19:53
If there is a real problem here, it will need to be fixed by the mod author, because this mod's metadata is in a metanetkan that he maintains:

- https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/ThrottleControlledAvionics.netkan
- https://raw.githubusercontent.com/allista/ThrottleControlledAvionics/master/ThrottleControlledAvionics.netkan

The CKAN team could help if the tags were wrong, but not much else.

**Comment by HebaruSan** [comment] 2020-09-11 20:11
This looks similar to #8085 and allista/AT_Utils#24 and KSP-CKAN/CKAN-meta#2133; there are two similar reports on this mod's forum thread:

![image](https://user-images.githubusercontent.com/1559108/92968411-957e1400-f46a-11ea-83ff-320e77958b99.png)
![image](https://user-images.githubusercontent.com/1559108/92968435-a464c680-f46a-11ea-8b24-ff45a079ca9b.png)

These versions might be incorrectly marked as compatible with KSP 1.9:

- https://github.com/KSP-CKAN/CKAN-meta/blob/master/ThrottleControlledAvionics/ThrottleControlledAvionics-v3.7.1.ckan
- https://github.com/KSP-CKAN/CKAN-meta/blob/master/ThrottleControlledAvionics/ThrottleControlledAvionics-v3.7.2.ckan

![image](https://user-images.githubusercontent.com/1559108/92968467-b7779680-f46a-11ea-85ca-71dbcfdf9d9d.png)

Confirmed, TCA is shipping with an incorrect version file.

```json
{ 
    "NAME":"ThrottleControlledAvionics",
    "URL":"https://raw.githubusercontent.com/allista/ThrottleControlledAvionics/master/GameData/ThrottleControlledAvionics/ThrottleControlledAvionics.version",
    "DOWNLOAD":"http://spacedock.info/mod/198/Throttle%20Controlled%20Avionics",
    "CHANGE_LOG_URL":"https://raw.githubusercontent.com/allista/ThrottleControlledAvionics/master/ChangeLog.md",
    "VERSION":
     {
         "MAJOR":3,
         "MINOR":7,
         "PATCH":2,
         "BUILD":0
     },
    "KSP_VERSION_MIN":
     {
         "MAJOR":1,
         "MINOR":9,
         "PATCH":0
     },
    "KSP_VERSION_MAX":
     {
         "MAJOR":1,
         "MINOR":10,
         "PATCH":0
     }
}
```

Re-opening since we can help the author with that as in the previously linked issue.

**Comment by HebaruSan** [comment] 2020-09-13 18:12
Thanks for letting us know. As of https://github.com/KSP-CKAN/CKAN-meta/commit/ed0e05d2bc9774f660756aba4419656c7db1c29a , CKAN should install the right version on KSP 1.9.1.

**Closed by HebaruSan** 2020-09-13 18:12 UTC
Labels: Support
