### ISSUE TITLE
[Mod] Can we add "RealShute" to the "ScrapYard" conflict section?

### ISSUE THREAD

**Issue by Artemonim** [KSP-CKAN/NetKAN#7977] opened 2020-06-16 20:33 UTC
Parachutes from "[RealShute](http://forum.kerbalspaceprogram.com/index.php?/topic/52931-0)" cannot be reused via "[ScrapYard](https://forum.kerbalspaceprogram.com/index.php?/topic/192456-*)", so I suggest adding RS to the list of conflicts. [I wrote this on mod's homepage, but the author doesn't respond to comments for at least a month.](https://forum.kerbalspaceprogram.com/index.php?/topic/192456-19x-scrapyard-the-common-part-inventory-2100kanford-and-sons-back-in-business-2020-mar-15/&do=findComment&comment=3789668)

**Comment by HebaruSan** [comment] 2020-06-16 20:36
Based on what?

**Comment by Artemonim** [comment] 2020-06-16 20:46
> Based on what?

[I recorded a video](https://www.youtube.com/watch?v=ZBmhgJ1PWcM) that shows that parts from RealShute are not replaced with parts stored in ScrapYard (and they should be — ScrapYard stores used and not destroyed parts for reuse). The same problem faced by another user of the mod. When used together with KCT, which calculates the construction time of new parts, this can become critical (in the video, this added almost 3 days to the build time).

**Comment by Artemonim** [comment] 2020-06-16 22:31
[I also notified the author of RS](https://forum.kerbalspaceprogram.com/index.php?/topic/52931-19-realchute-parachute-systems-v1476-180320/&do=findComment&comment=3804278), who is quite active in his topic, so we can wait for his response.

**Comment by HebaruSan** [comment] 2020-06-16 22:39
(It's RealChute, not RealShute. "Parachute" is spelled with a 'c'.)
Yes, if the author agrees, we can add a conflict. Otherwise we would have to investigate to make sure the problem is diagnosed correctly and the proposed solution is appropriate.

How likely is it that some users have both mods installed and are not bothered by this problem, but would be bothered by suddenly having to uninstall one or the other?

**Comment by Artemonim** [comment] 2020-06-17 05:57
> How likely is it that some users have both mods installed and are not bothered by this problem, but would be bothered by suddenly having to uninstall one or the other?

I think this can only noticeably interfere if used in combination with Kerbal Construction Time. Without KCT, you will spend more money on building a rocket than you should, but this is not critical and you may not even notice it.

[I also received a response from the author of RealChute](https://forum.kerbalspaceprogram.com/index.php?/topic/52931-19-realchute-parachute-systems-v1476-180320/&do=findComment&comment=3804456):
>First thing I'm noticing is the use of the stock chutes. They have an MM patch applied over them, and that might be what's conflicting. Try using the RealChute parts instead and see if that works. FAR's RealChute implementation also does not use an MM patch, so that would make sense why they work.

**Comment by HebaruSan** [comment] 2020-06-19 21:23
OK, in that case, it doesn't sound appropriate to add a conflict. Closing.

**Closed by HebaruSan** 2020-06-19 21:23 UTC
Labels: Needs looking into
