### ISSUE TITLE
Error after sitting for a while (still)

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/NetKAN#6664] opened 2018-08-07 10:52 UTC
Version 1.25.2
Windows 10 Pro

This may have been reported before, but now I have the full error, and it's also with the updated version:

Opened CKAN, played game, did updates, etc.  Worked fine
Left it overnight
Cam back in the morning, clicked "Refresh"
Got the following error:

Updating repositories...
Failed to download https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz: System.Net.WebException: An exception occurred during a WebClient request. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\jbb\AppData\Local\Temp\CdFileMgr\d684c8c9-22db-41.tmp'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at CKAN.Net.Download(String url, String filename, IUser user)
   at CKAN.Repo.UpdateRegistry(Uri repo, KSP ksp, IUser user)
Repository update failed!

**Comment by HebaruSan** [comment] 2018-08-07 14:55
Duplicate of KSP-CKAN/CKAN#2391 (based on the symptoms) and/or KSP-CKAN/CKAN#2342 (based on the exception). This suggests those two may have the same root cause.

Please post any updates there if you're able to figure out why the CdFileMgr folder is disappearing or failing to be created.

**Closed by HebaruSan** 2018-08-07 14:55 UTC
